# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  cypress: cypress-io/cypress@1

# $ brew install circleci
# $ circleci config process .circleci/config.yml
# workflows reference jobs, see https://github.com/cypress-io/circleci-orb/blob/master/docs/examples.md#using-node14
# https://docs.cypress.io/guides/guides/continuous-integration.html#CircleCI
workflows:
  version: 2
  build:
    jobs:
    # https://github.com/cypress-io/circleci-orb/blob/master/docs/examples.md#using-node14
    - cypress/install:
        executor: cypress/base-14
        cache-key: v1-dependencies-{{ checksum "yarn.lock" }}
        yarn: true

    - cypress/run:
        requires:
        - cypress/install

        pre-steps:
        - run:
            name: Lerna Prepare and Link 🔗
            command: yarn run lerna:prepare
        - run:
            name: Jest unit tests ❓
            command: yarn test

        executor: cypress/base-14
        start: yarn start:samples:app
        wait-on: http://localhost:3000
        record: true
        yarn: true
        verify-command: yarn cypress verify
        cache-key: v1-dependencies-{{ checksum "yarn.lock" }}